liip_imagine:
    driver: "gd"
    filter_sets:
        cache: ~
        my_thumb:
            quality: 75

            filters:
                thumbnail: { size: [360, 230], mode: outbound, allow_upscale: true, scale: {dim:[360, 230]}}