recaptcha:
  key: '6Lf2PIIbAAAAANQClPiqK3Ee9VoSt25Xg4kTG23e'
  secret: '6Lf2PIIbAAAAANgawFgM8-ol1NbSHT6krR-EeiPO'
services:
  recaptcha.type:
    class: Graficart\RecaptchaBundle\Type\RecaptchaSubmitType
    tags: ['form.type']
    arguments:
      $key: '6Lf2PIIbAAAAANQClPiqK3Ee9VoSt25Xg4kTG23e'