recaptcha:
  key: '6LdgXIIbAAAAACoCJHTxXTvRkTRdFCP8RJAbHEuq'
  secret: '6LdgXIIbAAAAAO6lkGh-omGWf6cstpowlHEmnmjB'
services:
   recaptcha.type:
    class: Graficart\RecaptchaBundle\Type\RecaptchaSubmitType
    tags: ['form.type']
    arguments:
      $key: '6LdgXIIbAAAAACoCJHTxXTvRkTRdFCP8RJAbHEuq'