#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home  :
    path: /
    controller: App\Controller\HomeController::index
tableau  :
    path: /tableau
    controller: App\Controller\HomeController::gotableau
customer  :
    path: /client
    controller: App\Controller\HomeController::gocustomer
